### ISSUE TITLE
Inheriting from these images

### ISSUE THREAD

**Issue by arokem** [pangeo-data/pangeo-docker-images#187]
Hello! I am interested in setting up a daskhub (following [these instruction](https://docs.dask.org/en/latest/setup/kubernetes-helm.html#helm-install-dask-for-mulitple-users)). IIUC, to configure user environments for this case, I would have to inherit from one of the images provided here. My question is: there are some special considerations for how to do that? Even more specifically: if I wrote a Dockerfile that has: 

```
FROM pangeo/pangeo-notebook:2021.02.07
```
At the top and then installed a bunch of my desired dependencies, could I build that with repo2docker? Because that would be nifty 😄 

As always, thanks for leading the way here!

**Comment by scottyhq** [comment]
Hi @arokem ;) 

I didn't realize the daskhub docs pointed to these images https://docs.dask.org/en/latest/setup/kubernetes-helm.html#matching-the-user-environment . @jacobtomlinson @TomAugspurger is there a dask image we can point to instead?

> FROM pangeo/pangeo-notebook:2021.02.07 

I don't think you want to do that because you'd get a bunch of geoscience-specific packages. But the base-image in this repository (`FROM pangeo/base-image:2021.02.07`) might be useful to you. If you want to go that route we either have this template repository https://github.com/pangeo-data/pangeo-binder-template, or if you can just directly modify our [Dockerfile](https://github.com/pangeo-data/pangeo-docker-images/blob/master/base-image/Dockerfile).

If you want to stick just with repo2docker for a single curated environment I recommend using https://github.com/jupyterhub/repo2docker-action. For daskhub in general I think the minimum requirement is the following libraries in your conda `environment.yml`:
```
- dask-gateway
- jupyterhub-singleuser
- ipywidgets
```

NOTE the versions of dask and dask-gateway in your conda environment need to match up with the chart version you are using (scroll to the bottom of this page: https://helm.dask.org). But currently, daskhub=4.5.7 --> dask-gateway=0.9 --> dask=2021)

**Comment by arokem** [comment]
Thanks @scottyhq ! Following your advice, I now have a repo that builds `FROM pangeo/base-image:2021.02.07`using pangrepo2docker/GHA (here: https://github.com/nrdg/autofq-daskhub).

Next, I need to figure out how to get this into the daskhub. But that might be something to follow up on the dask helmchart repo, which I am currently studying. To answer one of your questions, it seems to me that the dask documentation rightfully points to these images, because the base-image is the one that is used in the helm chart: https://github.com/dask/helm-chart/blob/main/daskhub/values.yaml#L55.

So, I think that I can close this issue, but feel free to reopen, if you think more discussion would be helpful.

**Comment by jacobtomlinson** [comment]
Raised dask/dask-docker#144
