### ISSUE TITLE
Add pageo-forge image

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-docker-images#326]
We'd like to add a new custom image to this project to support the pangeo-forge project. This will look a lot like the pangeo-notebook image, with the following differences:

- pin the version of prefect (i.e. `prefect=0.15.13`)
- include the latest version of pangeo-forge-recipes

I think we could build off the `base-notebook` image and follow a similar pattern to the pytorch and ml notebooks that use conda-lock to merge environment files.

cc @sharkinsspatial, @rabernat

**Comment by scottyhq** [comment]
Currently the [CI CondaLock action](https://github.com/pangeo-data/pangeo-docker-images/blob/master/.github/workflows/CondaLock.yml) re-solves every image so that all images have the same core package versions, and repository tags apply to *all* Docker images. This works well for a synched set of images made available via JupyterHub, but might be an inconvenience if for example you only want to update and tag a release of the pangeo-forge image...

The alternative of course is just to have a separate repository that builds off the base docker image: https://github.com/microsoft/planetary-computer-containers

**Comment by cisaacstern** [comment]
Yes, the `pangeo-docker-images` release cycle (every two weeks, IIUC) should be frequent enough for our needs.

**Comment by jhamman** [comment]
> @jhamman Do we need a custom image for pangeo-forge or is including pangeo-forge-recipes and pinning prefect in the pangeo-notebook image sufficient.

This will be a fine place to start. It is possible that conflicts will emerge as slow-to-update pins (i.e. prefect) go out of date. If that ends up being a problem, we can create a new image (here or elsewhere).
