### ISSUE TITLE
Document ML-image tag/GPU type/CUDA compatibility table

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-docker-images#390]
> I think it would be very useful to have a table of cuda versions and the pangeo docker images they are compatible with. 

from @yuvipanda in https://github.com/pangeo-data/pangeo-docker-images/issues/387#issuecomment-1276732810 

The images have cuda libraries that are only compatible with certain GPUs (K80, T4, etc)
https://github.com/pangeo-data/pangeo-docker-images/blob/118d49782bac9486d07bcc1b6231067473bcfa7b/ml-notebook/packages.txt#L96-L97

Would be great to document this in the [readme](https://github.com/pangeo-data/pangeo-docker-images#dask-gateway-compatibility) @ngam or @weiji14 any chance you'd like to create a short compatibility table? Or add a short message and link to the relevant NVIDIA docs?

**Comment by weiji14** [comment]
The K80s (Kepler generation, 2014) are a special case since later generation NVIDIA CUDA drivers (Maxwell onwards) have better forward compatibility with cudatoolkit, see https://docs.nvidia.com/deploy/cuda-compatibility/#forward-compatibility-title. Given the discussion in https://github.com/2i2c-org/infrastructure/issues/1765 on updating all the Pangeo hub clusters to T4s (can't say I didn't see this coming), I think we can probably just leave it at that (unless we expect to be supporting K80s for much longer).

Pro tip: The general rule of thumb [I follow](https://github.com/weiji14/deepbedmap/commit/4dd92c8f29b007619ca905a338ffb7050f5157ec) is to always have the latest CUDA **driver** version, which should work with any cuda**toolkit** (CTK) version 6.5 or above (though I recommend at least cudatoolkit 9.0).

![CUDA compatibility](https://user-images.githubusercontent.com/23487320/195747231-dd7f7dbe-54e0-4439-94f7-1ae1eeedde24.png)

**Comment by yuvipanda** [comment]
I'd say in that case the suggestion would be to document *preferred GPUs*, and say folks should prefer T4 (if that is actually the case - I don't know!). I'm not super well versed in GPU usage, so would love some guidance that says 'just use these GPUs' from folks in the knoew.

**Comment by weiji14** [comment]
> @weiji14 do you have access to these hubs? If not, the best person to document this is going to be @dhruvbalwada who will have hands-on experience with the systems/hubs in question.

If you mean the m2lines hubs, then no. Probably best to ask @dhruvbalwada.

**Comment by scottyhq** [comment]
Thanks for that table @weiji14 I'm embarrassed to say I had to go to https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#Tesla in order to realize the first letter of the short name corresponds to "Hardware Generation"...

```
K80 = Kepler
T4 = Turing
V100 = Volta
```

**Comment by dhruvbalwada** [comment]
TBH I am very confused. 

Here is the original problem (https://github.com/pangeo-data/pangeo-docker-images/issues/387) - we had to downgrade the cuda-nvcc to match the driver version that is available. This was because of the XLA issue that ngam mentions above. 

@yuvipanda - what is setting the driver version that we end up with? Can this not be higher than 11.6 (latest), if we drop support for K80s?

**Comment by dhruvbalwada** [comment]
Thank you @weiji14, this is extremely helpful - glad to be learning more about this.

**Comment by yuvipanda** [comment]
@dhruvbalwada it's set by whatever version Google supports, and we're currently at the latest version they support! https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#installing_drivers has the table. T4 and K80 are handled separately, so dropping support for K80 won't do much for T4 here.
