### ISSUE TITLE
update base image to use latest mamba

### ISSUE THREAD

**Issue by ngam** [pangeo-data/pangeo-docker-images#464]
Currently, the base image uses mamba 1.0.0

---

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by weiji14** [comment]
Seems like the `base-image` is just using the latest Mambaforge https://github.com/pangeo-data/pangeo-docker-images/blob/master/base-image/Dockerfile#L65-L67
which hasn't had a release since Feb 2023, see latest one at https://github.com/conda-forge/miniforge/releases/tag/23.1.0-1. We could do a `mamba update mamba` in he base-image, or try to get upstream to make a new release with a newer mamba perhaps.

**Comment by weiji14** [comment]
Seems like the `base-image` is just using the latest Mambaforge https://github.com/pangeo-data/pangeo-docker-images/blob/master/base-image/Dockerfile#L65-L67
which hasn't had a release since Feb 2023, see latest one at https://github.com/conda-forge/miniforge/releases/tag/23.1.0-1. We could do a `mamba update mamba` in he base-image, or try to get upstream to make a new release with a newer mamba perhaps.

**Comment by weiji14** [comment]
From the `base-image` build logs at https://github.com/pangeo-data/pangeo-docker-images/actions/runs/5218654046/jobs/9419638775#step:7:370, I see that `mamba=1.4.1` is installed. On Mambaforge, there is a hard pin to `mamba=1.4.2` at https://github.com/conda-forge/miniforge/blob/6fee91c961ff381b5a612ce8133805c0b806782b/Miniforge3/construct.yaml#L32-L33. So I'm not sure where your `mamba=1.0.0` is coming from?

Just to double-check, I did a `docker run --rm -it quay.io/pangeo/base-notebook mamba --version` (couldn't get it to work for `base-image` for some reason), and it reports:

```
2023.06.07: Pulling from pangeo/base-notebook
Digest: sha256:0c364c664832848fbbb12b4e1dc4588fbd5e697204cb9cee170196e3bcb1ca68
Status: Downloaded newer image for quay.io/pangeo/base-notebook:2023.06.07
mamba 1.4.1
conda 23.1.0
```

Are you using the `base-image` from a managed JupyterHub that has pinned to an old version of `base-image` perhaps?

**Comment by weiji14** [comment]
> > managed JupyterHub
> 
> Yes, sorry, I should have been clearer. I was referring to the base-image used by pangeo.io/cloud

Right, so that one links to https://us-central1-b.gcp.pangeo.io/. Maybe post an issue at https://github.com/pangeo-data/pangeo-cloud-federation? Not sure if those are being actively maintained anymore though.
