### ISSUE TITLE
Graphical issues  dask-labextension

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/pangeo-docker-images#467]
**Describe the bug**
The usual tabs of the dask-labextension look wonky and show no logos. Super minor issue (that should be adressed upstream I guess), but still wanted to mention it.

**To Reproduce**
1. Open any window from the dask-labextension sidebar

**Expected behavior**
I expected the logos/tab riders to look cleaner.

**Docker Image Version (e.g. quay.io/pangeo/ml-notebook:2023.02.27):**

**Infrastructure (Where you are running this image):**
- LEAP-Pangeo JupyterHub (leap.2i2c.cloud)

**Screenshots**
The sidebar icon: 
<img width="33" alt="image" src="https://github.com/pangeo-data/pangeo-docker-images/assets/14314623/d8a25c93-c40f-483a-bd25-943969b6f0f7">

The actual windows
<img width="851" alt="image" src="https://github.com/pangeo-data/pangeo-docker-images/assets/14314623/a30e8edc-b3d1-4d4d-967f-1ff9b15c8529">

**Additional context**
Contrary to e.g. #466 this problem is persistent on both safari and chrome

**Comment by weiji14** [comment]
> I just tried this with `pangeo/pangeo-notebook:2023.05.18`, and did not see these issues. I suspect this is a problem with jupyterlab `4.0.2`?

Thanks for the detailed bug report @jbusecke! Looking at the differences from https://github.com/pangeo-data/pangeo-docker-images/compare/2023.05.18...2023.06.20, it looks like we upgraded jupyterlab from 3.6.3 to 4.0.2, so that might be it. Tag `2023.06.07` uses jupyterlab 4.0.1 also, so that probably won't work either.

It looks like JupyterLab 4 compatibility is being worked on at https://github.com/dask/dask-labextension/pull/263, we'll make sure to update things as soon as they release a new version with that patch.

**Comment by mahendrapaipuri** [comment]
This has been fixed in [dask-labextension#262](https://github.com/dask/dask-labextension/pull/262). But I think there was no release with this PR after. If you install `dask-labextension` from `main`, it should work.

**Comment by jbusecke** [comment]
Thanks @mahendrapaipuri Ill wait for the next pangeo-docker-image release which will hopefully include this. Feel free to close this or keep open until new release

**Comment by weiji14** [comment]
We've updated `dask-labextension` to [7.0.0](https://github.com/dask/dask-labextension/releases/tag/7.0.0) (released 5 Aug 2023) in #481, and tagged [`2023.09.11`](https://github.com/pangeo-data/pangeo-docker-images/releases/tag/2023.09.11) and [`2023.09.19`](https://github.com/pangeo-data/pangeo-docker-images/releases/tag/2023.09.19) since. Can you check if the issue has been resolved @jbusecke? Might need to point the LEAP JupyterHub to one of these newer docker images first.

**Comment by jbusecke** [comment]
Just tested and looks good. Thanks so much! I will close this now.
