### ISSUE TITLE
Confusing tags on dockerhub

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-docker-images#80]
Looking at DockerHub's list of recent tags for the `base-image`, I'm noticing some concerning inconsistencies: 

![image](https://user-images.githubusercontent.com/2443309/84284200-bc861c00-aaf0-11ea-8d15-d1528979de12.png)

Despite #79 being merged last night, the `2020.06.10` tag doesn't appear in the tags list. Also, the latest and the master tags differ. 

@scottyhq - ideas here? I'm at a loss.

**Comment by scottyhq** [comment]
@jhamman - this is expected behavior, see https://github.com/pangeo-data/pangeo-docker-images#image-tagging-and-continuous-building. You have to manually push a tag `git pull upstream master; git tag 2020.06.10; git push upstream --tags` if you want the calver tag + latest tag.

**Comment by jhamman** [comment]
@scottyhq - thanks for the response. My only follow up question is how do we decide to make a "production" release? I think my preference would be to tag calver snapshots on each push to master like we did over in pangeo-stacks.

**Comment by scottyhq** [comment]
> My only follow up question is how do we decide to make a "production" release? 

The goal with the current setup was to keep just one branch (master) instead of staging and prod, and point staging hubs and staging binders at the 'master' tag for testing. Once things seem to be working ok, manually tag with calver + latest. 

It would be nice if we had some full integration tests (e.g. verify dask clusters launch and run some basic analysis... maybe with binderbot). I like having fewer calver 'production' releases to keep track of. Ideally, every calver tag would be guaranteed to work, but so far our operating model has unfortunately been 1) calver tag for image with new dask versions 2) discover something broke with dashboard or gateway compatibility 3) quickly rebuild with patched versions and new calver tag.
