### ISSUE TITLE
Remove dask-kubernetes config

### ISSUE THREAD

**Issue by scottyhq** [pangeo-data/pangeo-docker-images#94]
@TomAugspurger , I believe we can now fully remove dask-kubernetes config from the images since this config is now taken care of in the dask-gateway helm chart, correct?

https://github.com/pangeo-data/pangeo-docker-images/blob/e3fd4ae4a797a78072b403815791b0dda5318066/base-image/dask_config.yml#L27-L51

**Comment by scottyhq** [comment]
The question here is where images in this repo should be solely intended to run on Pangeo JupyterHubs or also potentially used in other settings (xref https://github.com/pangeo-data/pangeo-docker-images/issues/112)

For example, you might want to run one of these docker images locally without dask as described in the readme:

Or you might want to run a single-user deployment of the dask helm chart (https://github.com/dask/helm-chart), in which case maybe it's helpful to keep  this config file in but remove the jupyterhub environment variables {JUPYTERHUB_USER}? Thoughts @TomAugspurger ?

**Comment by TomAugspurger** [comment]
I'm not sure what's best here. I've always found including the Dask configs
here a bit strange, since

1. They can be difficult to debug (what values they're setting, where
they're coming from)
2. They feel like they're making application-specific choices (number of
threads per worker) in a base image

So perhaps I'm arguing for removing them and documenting how they should be
used at the application level? I'm not really sure.
